function model = train_pca_svm_model(trainDir, pcaDim, svmC, options)
%TRAIN_PCA_SVM_MODEL Hand-written PCA plus hand-written SVM training contract.

    model = struct('status', 'todo', 'message', 'hand-written train_pca_svm_model not implemented', ...
        'labels', {{}}, 'imageSize', [], 'meanFace', [], 'eigenfaces', [], ...
        'pcaDim', pcaDim, 'svmC', svmC, 'svmParams', [], 'trainSummary', [], ...
        'trainDir', trainDir, 'options', options);
end
