function schema = shared_state_schema()
%SHARED_STATE_SCHEMA Document the minimum shared state contract.

    schema = { ...
        'currentImage', ...
        'config', ...
        'rawFaceDir', ...
        'processedFaceDir', ...
        'defaultTrainDir', ...
        'defaultTestDir', ...
        'defaultModelPath', ...
        'currentImagePath', ...
        'currentGrayImage', ...
        'currentProcessedImage', ...
        'currentFaceBox', ...
        'currentFaceInfo', ...
        'currentAlignInfo', ...
        'currentAlignedFace', ...
        'currentCameraFrame', ...
        'camera', ...
        'lastReplayPackage', ...
        'model', ...
        'batchResult', ...
        'singleResult', ...
        'realtimeResult', ...
        'datasetManifest', ...
        'defaultPcaDim', ...
        'defaultSvmC', ...
        'defaultSvmMaxEpochs', ...
        'defaultSvmLearningRate', ...
        'defaultSvmLearningRateDecay'};
end

