function schema = shared_state_schema()
%SHARED_STATE_SCHEMA Document the minimum shared state contract.

    schema = { ...
        'currentImage', ...
        'currentImagePath', ...
        'currentGrayImage', ...
        'currentFaceBox', ...
        'currentAlignedFace', ...
        'currentCameraFrame', ...
        'lastReplayPackage', ...
        'model', ...
        'batchResult', ...
        'singleResult', ...
        'realtimeResult', ...
        'datasetManifest', ...
        'defaultPcaDim', ...
        'defaultSvmC'};
end

