from __future__ import annotations

import argparse
import csv
import shutil
from pathlib import Path

import cv2
import numpy as np


POINT_NAMES = ("left_eye", "right_eye", "mouth")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Manually align flagged face images by clicking left eye, right eye, and mouth."
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=Path("../data/aligned_faces/alignment_split_manifest.csv"),
        help="alignment_split_manifest.csv generated by prepare_aligned_dataset.py.",
    )
    parser.add_argument("--width", type=int, default=92, help="Output image width.")
    parser.add_argument("--height", type=int, default=112, help="Output image height.")
    parser.add_argument(
        "--all",
        action="store_true",
        help="Process all rows instead of only needs_manual_review=1 rows.",
    )
    parser.add_argument(
        "--backup-dir",
        type=Path,
        default=None,
        help="Backup directory for images replaced by this script. Defaults to manifest_dir/manual_backup.",
    )
    return parser.parse_args()


def read_image_unicode(path: Path) -> np.ndarray | None:
    data = np.fromfile(str(path), dtype=np.uint8)
    if data.size == 0:
        return None
    return cv2.imdecode(data, cv2.IMREAD_COLOR)


def write_image_unicode(path: Path, image: np.ndarray) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    ok, encoded = cv2.imencode(path.suffix or ".jpg", image)
    if not ok:
        return False
    encoded.tofile(str(path))
    return True


def target_points(width: int, height: int) -> np.ndarray:
    return np.array(
        [
            [0.32 * width, 0.38 * height],
            [0.68 * width, 0.38 * height],
            [0.50 * width, 0.72 * height],
        ],
        dtype=np.float32,
    )


def normalize_gray(gray: np.ndarray) -> np.ndarray:
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    return clahe.apply(gray)


def align_from_points(
    image_bgr: np.ndarray,
    points: list[tuple[float, float]],
    output_size: tuple[int, int],
) -> np.ndarray:
    source = np.array(points, dtype=np.float32)
    transform = cv2.getAffineTransform(source, target_points(output_size[0], output_size[1]))
    aligned = cv2.warpAffine(
        image_bgr,
        transform,
        output_size,
        flags=cv2.INTER_LINEAR,
        borderMode=cv2.BORDER_REFLECT_101,
    )
    return normalize_gray(cv2.cvtColor(aligned, cv2.COLOR_BGR2GRAY))


def fit_for_display(image: np.ndarray, max_side: int = 900) -> tuple[np.ndarray, float]:
    height, width = image.shape[:2]
    scale = min(1.0, max_side / max(height, width))
    if scale == 1.0:
        return image.copy(), scale
    resized = cv2.resize(image, (round(width * scale), round(height * scale)), interpolation=cv2.INTER_AREA)
    return resized, scale


def draw_points(display: np.ndarray, display_points: list[tuple[int, int]]) -> np.ndarray:
    canvas = display.copy()
    for index, point in enumerate(display_points):
        color = (0, 255, 0) if index < 2 else (0, 180, 255)
        cv2.drawMarker(canvas, point, color, cv2.MARKER_CROSS, 22, 2)
        cv2.putText(
            canvas,
            POINT_NAMES[index],
            (point[0] + 8, point[1] - 8),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.55,
            color,
            2,
            cv2.LINE_AA,
        )
    next_index = len(display_points)
    if next_index < len(POINT_NAMES):
        prompt = f"Click {POINT_NAMES[next_index]} | u undo | r reset | n skip | q quit"
    else:
        prompt = "s save | r redo | n skip | q quit"
    cv2.rectangle(canvas, (0, 0), (canvas.shape[1], 34), (0, 0, 0), -1)
    cv2.putText(canvas, prompt, (8, 23), cv2.FONT_HERSHEY_SIMPLEX, 0.62, (255, 255, 255), 2, cv2.LINE_AA)
    return canvas


def collect_points(image_bgr: np.ndarray, title: str) -> list[tuple[float, float]] | None:
    display, scale = fit_for_display(image_bgr)
    display_points: list[tuple[int, int]] = []

    def on_mouse(event, x, y, _flags, _param) -> None:
        if event == cv2.EVENT_LBUTTONDOWN and len(display_points) < 3:
            display_points.append((x, y))

    cv2.namedWindow(title, cv2.WINDOW_AUTOSIZE)
    cv2.setMouseCallback(title, on_mouse)

    while True:
        cv2.imshow(title, draw_points(display, display_points))
        key = cv2.waitKey(30) & 0xFF

        if key == ord("q"):
            cv2.destroyWindow(title)
            raise KeyboardInterrupt
        if key == ord("n"):
            cv2.destroyWindow(title)
            return None
        if key == ord("u") and display_points:
            display_points.pop()
        if key == ord("r"):
            display_points.clear()
        if key == ord("s") and len(display_points) == 3:
            cv2.destroyWindow(title)
            return [(x / scale, y / scale) for x, y in display_points]


def confirm_preview(aligned_gray: np.ndarray, title: str) -> str:
    preview = cv2.resize(aligned_gray, (aligned_gray.shape[1] * 3, aligned_gray.shape[0] * 3), interpolation=cv2.INTER_NEAREST)
    cv2.namedWindow(title, cv2.WINDOW_AUTOSIZE)
    while True:
        canvas = cv2.cvtColor(preview, cv2.COLOR_GRAY2BGR)
        cv2.rectangle(canvas, (0, 0), (canvas.shape[1], 34), (0, 0, 0), -1)
        cv2.putText(
            canvas,
            "preview: s save | r redo | n skip | q quit",
            (8, 23),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.62,
            (255, 255, 255),
            2,
            cv2.LINE_AA,
        )
        cv2.imshow(title, canvas)
        key = cv2.waitKey(30) & 0xFF
        if key in (ord("s"), ord("r"), ord("n"), ord("q")):
            cv2.destroyWindow(title)
            return chr(key)


def read_manifest(path: Path) -> tuple[list[dict[str, str]], list[str]]:
    with path.open("r", newline="", encoding="utf-8-sig") as file:
        reader = csv.DictReader(file)
        rows = list(reader)
        fieldnames = list(reader.fieldnames or [])
    return rows, fieldnames


def write_manifest(path: Path, rows: list[dict[str, str]], fieldnames: list[str]) -> None:
    with path.open("w", newline="", encoding="utf-8-sig") as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def backup_existing(path: Path, backup_dir: Path, label: str) -> None:
    if not path.exists():
        return
    target = backup_dir / label / path.name
    target.parent.mkdir(parents=True, exist_ok=True)
    if not target.exists():
        shutil.copy2(path, target)


def save_aligned(row: dict[str, str], aligned_gray: np.ndarray, backup_dir: Path) -> None:
    label = row["label"]
    for key in ("aligned_path", "split_path"):
        path_text = row.get(key, "")
        if not path_text:
            continue
        path = Path(path_text)
        backup_existing(path, backup_dir, label)
        if not write_image_unicode(path, aligned_gray):
            raise RuntimeError(f"Failed to write image: {path}")


def ensure_fields(fieldnames: list[str]) -> list[str]:
    additions = ["manual_left_eye_x", "manual_left_eye_y", "manual_right_eye_x", "manual_right_eye_y", "manual_mouth_x", "manual_mouth_y"]
    for name in additions:
        if name not in fieldnames:
            fieldnames.append(name)
    return fieldnames


def main() -> None:
    args = parse_args()
    manifest_path = args.manifest.resolve()
    backup_dir = args.backup_dir.resolve() if args.backup_dir else manifest_path.parent / "manual_backup"
    rows, fieldnames = read_manifest(manifest_path)
    fieldnames = ensure_fields(fieldnames)

    target_indices = [
        index
        for index, row in enumerate(rows)
        if args.all or row.get("needs_manual_review", "") == "1" or row.get("status", "") == "fallback_resize"
    ]

    print(f"manifest: {manifest_path}")
    print(f"images to review: {len(target_indices)}")
    print("Click order: left eye, right eye, mouth. Press s to save after three clicks.")

    saved = 0
    skipped = 0

    try:
        for position, row_index in enumerate(target_indices, start=1):
            row = rows[row_index]
            source_path = Path(row["source"])
            image = read_image_unicode(source_path)
            if image is None:
                print(f"read failed: {source_path}")
                skipped += 1
                continue

            while True:
                title = f"{position}/{len(target_indices)} {source_path.name}"
                points = collect_points(image, title)
                if points is None:
                    print(f"skipped: {source_path.name}")
                    skipped += 1
                    break

                aligned = align_from_points(image, points, (args.width, args.height))
                decision = confirm_preview(aligned, f"preview {source_path.name}")
                if decision == "q":
                    raise KeyboardInterrupt
                if decision == "r":
                    continue
                if decision == "n":
                    print(f"skipped: {source_path.name}")
                    skipped += 1
                    break

                save_aligned(row, aligned, backup_dir)
                row["status"] = "manual_aligned"
                row["needs_manual_review"] = "0"
                row["manual_left_eye_x"] = f"{points[0][0]:.3f}"
                row["manual_left_eye_y"] = f"{points[0][1]:.3f}"
                row["manual_right_eye_x"] = f"{points[1][0]:.3f}"
                row["manual_right_eye_y"] = f"{points[1][1]:.3f}"
                row["manual_mouth_x"] = f"{points[2][0]:.3f}"
                row["manual_mouth_y"] = f"{points[2][1]:.3f}"
                write_manifest(manifest_path, rows, fieldnames)
                saved += 1
                print(f"saved: {source_path.name}")
                break
    except KeyboardInterrupt:
        print("quit requested; manifest has been saved for completed images.")
    finally:
        cv2.destroyAllWindows()

    print("=" * 60)
    print(f"saved: {saved}")
    print(f"skipped: {skipped}")
    print(f"backup: {backup_dir}")
    print("=" * 60)


if __name__ == "__main__":
    main()
