function panel = create_cute_panel(parent, titleText, theme, bgColor)
%CREATE_CUTE_PANEL Create a pastel section panel with shared styling.

    if nargin < 3 || isempty(theme)
        theme = get_ui_theme();
    end
    if nargin < 4 || isempty(bgColor)
        bgColor = theme.colors.cream;
    end

    panel = uipanel(parent, ...
        'Title', titleText, ...
        'BackgroundColor', bgColor, ...
        'ForegroundColor', theme.colors.ink, ...
        'FontName', theme.fonts.english, ...
        'FontWeight', 'bold', ...
        'FontSize', theme.sizes.sectionTitle, ...
        'BorderType', 'line', ...
        'BorderColor', theme.colors.panelLine);
end
